name       : python-pikepdf
version    : 1.15.1
release    : 2
source     :
    - https://github.com/pikepdf/pikepdf/archive/v1.15.1.tar.gz : d89369fa99123275c541cee6e6ac3b95558b0526e6f725182fa6c79d9e8d3076
homepage   : https://github.com/pikepdf/pikepdf
license    : MPL-2.0
component  : programming.python
summary    : A Python library for reading and writing PDF, powered by qpdf
description: |
    Pikepdf is a Python library for reading and writing PDF files.
builddeps  :
    - pkgconfig(libqpdf)
    - pkgconfig(python3)
    - pybind11
    - python-setuptools-scm-git-archive
rundeps    :
    - python-lxml
build      : |
    %python3_setup
install    : |
    %python3_install
