name       : python-pikepdf
version    : 6.2.1
release    : 22
source     :
    - https://github.com/pikepdf/pikepdf/archive/refs/tags/v6.2.1.tar.gz : d568361f3e484e4bf20f3e9d9c4b452757b6cb409fd8414a314dc076042e4f0a
homepage   : https://github.com/pikepdf/pikepdf
license    : MPL-2.0
component  : programming.python
summary    : A Python library for reading and writing PDF, powered by qpdf
description: |
    Pikepdf is a Python library for reading and writing PDF files. It is based on QPDF, a powerful PDF manipulation and repair library.
builddeps  :
    - pkgconfig(libqpdf)
    - pkgconfig(python3)
    - pybind11
    - python-setuptools-scm-git-archive
rundeps    :
    - python-deprecation
    - python-lxml
    - python-packaging
    - python-pillow
build      : |
    %python3_setup
install    : |
    %python3_install
