name       : python-pikepdf
version    : 4.0.1
release    : 9
source     :
    - https://github.com/pikepdf/pikepdf/archive/refs/tags/v4.0.1.tar.gz : ea3726a92bbffb7bfdafc02930741aac4b25149ab068813f2d78029c3d83023f
homepage   : https://github.com/pikepdf/pikepdf
license    : MPL-2.0
component  : programming.python
summary    : A Python library for reading and writing PDF, powered by qpdf
description: |
    Pikepdf is a Python library for reading and writing PDF files. It is based on QPDF, a powerful PDF manipulation and repair library.
builddeps  :
    - pkgconfig(libqpdf)
    - pkgconfig(python3)
    - pybind11
    - python-dateutil
    - python-hypothesis
    - python-lxml
    - python-pillow
    - python-psutil
    - python-pytest
    - python-setuptools-scm-git-archive
    - python-toml
rundeps    :
    - python-lxml
    - python-pillow
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
