name       : python-pikepdf
version    : 2.13.0
release    : 8
source     :
    - https://github.com/pikepdf/pikepdf/archive/refs/tags/v2.13.0.tar.gz : 4266fe3f2ee40c1c9e652eeeffb9ac1534da9444a40b8c24b22544f11a349632
homepage   : https://github.com/pikepdf/pikepdf
license    : MPL-2.0
component  : programming.python
summary    : A Python library for reading and writing PDF, powered by qpdf
description: |
    Pikepdf is a Python library for reading and writing PDF files. It is based on QPDF, a powerful PDF manipulation and repair library.
builddeps  :
    - pkgconfig(libqpdf)
    - pkgconfig(python3)
    - pybind11
    - python-dateutil
    - python-hypothesis
    - python-lxml
    - python-pillow
    - python-psutil
    - python-pytest
    - python-setuptools-scm-git-archive
rundeps    :
    - python-lxml
    - python-pillow
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-tests-in-setup.cfg.patch
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
