name       : python-pikepdf
version    : 1.19.3
release    : 5
source     :
    - https://github.com/pikepdf/pikepdf/archive/v1.19.3.tar.gz : 3bb981b9d001f2a4166196b27de81487b4f7e25284eee516e9ed50971130a586
homepage   : https://github.com/pikepdf/pikepdf
license    : MPL-2.0
component  : programming.python
summary    : A Python library for reading and writing PDF, powered by qpdf
description: |
    Pikepdf is a Python library for reading and writing PDF files. It is based on QPDF, a powerful PDF manipulation and repair library.
builddeps  :
    - pkgconfig(libqpdf)
    - pkgconfig(python3)
    - pybind11
    - python-setuptools-scm-git-archive
rundeps    :
    - python-lxml
    - python-pillow
build      : |
    %python3_setup
install    : |
    %python3_install
