name       : python-pikepdf
version    : 4.4.1
release    : 15
source     :
    - https://files.pythonhosted.org/packages/source/p/pikepdf/pikepdf-4.4.1.tar.gz : c25d4c7673f9588d1f98bca498db98ba675070dc89ffffe50b3b124d4a005df9
homepage   : https://github.com/pikepdf/pikepdf
license    : MPL-2.0
component  : programming.python
summary    : A Python library for reading and writing PDF, powered by qpdf
description: |
    Pikepdf is a Python library for reading and writing PDF files. It is based on QPDF, a powerful PDF manipulation and repair library.
builddeps  :
    - pkgconfig(libqpdf)
    - pkgconfig(python3)
    - pybind11
    - python-setuptools-scm-git-archive
rundeps    :
    - python-lxml
    - python-packaging
    - python-pillow
build      : |
    %python3_setup
install    : |
    %python3_install
