name       : python-pikepdf
version    : 4.3.1
release    : 14
source     :
    - https://github.com/pikepdf/pikepdf/archive/refs/tags/v4.3.1.tar.gz : ac5b32cb1c095b75ba93e4aa78c675793bb52ddf86f3bed9ff546a8c8901058e
homepage   : https://github.com/pikepdf/pikepdf
license    : MPL-2.0
component  : programming.python
summary    : A Python library for reading and writing PDF, powered by qpdf
description: |
    Pikepdf is a Python library for reading and writing PDF files. It is based on QPDF, a powerful PDF manipulation and repair library.
builddeps  :
    - pkgconfig(libqpdf)
    - pkgconfig(python3)
    - pybind11
    - python-dateutil
    - python-hypothesis
    - python-lxml
    - python-pillow
    - python-psutil
    - python-pytest
    - python-setuptools-scm-git-archive
    - python-toml
rundeps    :
    - python-lxml
    - python-packaging
    - python-pillow
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
